"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const blockchainModels_1 = require("./blockchainModels");
const A = new blockchainModels_1.Wallet();
const B = new blockchainModels_1.Wallet();
const C = new blockchainModels_1.Wallet();
A.sendMoney(50, B.publicKey);
B.sendMoney(23, C.publicKey);
C.sendMoney(20, A.publicKey);
(0, blockchainModels_1.printChain)();
